# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Workshop Registration Tests

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        cd workshop-registration
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
    - name: Test with pytest
      env: 
        ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}
        CLIENT_ID: ${{ secrets.ZOOM_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.ZOOM_CLIENT_SECRET }}
        TEST_GROUP_ID: ${{ secrets.ZOOM_GROUP_ID }}
        TEST_USER_ID: ${{ secrets.ZOOM_USER_ID }}
      run: |
        cd workshop-registration
        python -m pytest
    - name: Test with behave
      env: 
        ACCOUNT_ID: ${{ secrets.ZOOM_ACCOUNT_ID }}
        CLIENT_ID: ${{ secrets.ZOOM_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.ZOOM_CLIENT_SECRET }}
        TEST_GROUP_ID: ${{ secrets.ZOOM_GROUP_ID }}
        TEST_USER_ID: ${{ secrets.ZOOM_USER_ID }}
      run: |
        cd workshop-registration
        behave
    - name: Test with mypy
      run: |
        cd workshop-registration
        mypy .
